# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-04 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('official_name', models.CharField(blank=True, max_length=50)),
                ('birthday', models.DateField(blank=True, null=True)),
                ('micro_num', models.CharField(blank=True, max_length=50)),
                ('rec_num', models.CharField(blank=True, max_length=50)),
                ('tattoo', models.CharField(blank=True, max_length=50)),
                ('insurance', models.TextField(blank=True, max_length=255)),
                ('passport', models.CharField(blank=True, max_length=100)),
                ('other_info', models.TextField(blank=True, max_length=512)),
                ('death_day', models.DateField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinic_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('operations_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('lab_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('accessories_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('medicines_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('diet_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('km_payment', models.DecimalField(decimal_places=2, max_digits=10)),
                ('due_date', models.DateField()),
                ('paid_time', models.DateField()),
                ('paid_value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('index_number', models.IntegerField()),
                ('other_info', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
            ],
        ),
        migrations.CreateModel(
            name='ItemBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, max_length=1000)),
                ('stock_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=9)),
                ('price', models.DecimalField(decimal_places=2, max_digits=9)),
                ('barcode', models.CharField(blank=True, max_length=100)),
                ('count_type', models.CharField(choices=[('pcs', 'kpl'), ('ml', 'ml'), ('l', 'l'), ('mg', 'mg'), ('g', 'g'), ('kg', 'kg')], default='pcs', max_length=10)),
                ('archive', models.BooleanField(default=False)),
                ('item_type', models.CharField(default='Item', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=100)),
                ('phonenumber', models.CharField(blank=True, max_length=100)),
                ('email', models.EmailField(blank=True, max_length=100)),
                ('other_info', models.TextField(blank=True, max_length=500)),
                ('archive', models.BooleanField(default=False)),
                ('animals', models.ManyToManyField(blank=True, to='VetApp.Animal')),
            ],
        ),
        migrations.CreateModel(
            name='PostOffice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Sex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Specie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SpecieDescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=1000)),
                ('specie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Specie')),
            ],
        ),
        migrations.CreateModel(
            name='Vet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vet_number', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_reason', models.CharField(blank=True, max_length=1000)),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('archive', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VisitAnimal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('anamnesis', models.CharField(blank=True, max_length=1000)),
                ('status', models.CharField(blank=True, max_length=1000)),
                ('diagnosis', models.CharField(blank=True, max_length=1000)),
                ('treatment', models.CharField(blank=True, max_length=1000)),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Animal')),
                ('items', models.ManyToManyField(blank=True, to='VetApp.Item')),
                ('operations', models.ManyToManyField(blank=True, to='VetApp.Operation')),
            ],
        ),
        migrations.CreateModel(
            name='VisitItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.IntegerField(default=1)),
                ('Item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Item')),
                ('visit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Visit')),
            ],
        ),
        migrations.AddField(
            model_name='visit',
            name='items',
            field=models.ManyToManyField(blank=True, through='VetApp.VisitItems', to='VetApp.Item'),
        ),
        migrations.AddField(
            model_name='visit',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Owner'),
        ),
        migrations.AddField(
            model_name='visit',
            name='vet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Vet'),
        ),
        migrations.AddField(
            model_name='visit',
            name='visitanimals',
            field=models.ManyToManyField(blank=True, to='VetApp.VisitAnimal'),
        ),
        migrations.AddField(
            model_name='race',
            name='specie',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Specie'),
        ),
        migrations.AlterUniqueTogether(
            name='postoffice',
            unique_together=set([('name', 'number')]),
        ),
        migrations.AddField(
            model_name='owner',
            name='post_office',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VetApp.PostOffice'),
        ),
        migrations.AddField(
            model_name='itembase',
            name='specie_description',
            field=models.ManyToManyField(to='VetApp.SpecieDescription'),
        ),
        migrations.AddField(
            model_name='item',
            name='base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.ItemBase'),
        ),
        migrations.AddField(
            model_name='bill',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='VetApp.Visit'),
        ),
        migrations.AddField(
            model_name='animal',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VetApp.Color'),
        ),
        migrations.AddField(
            model_name='animal',
            name='race',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VetApp.Race'),
        ),
        migrations.AddField(
            model_name='animal',
            name='sex',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VetApp.Sex'),
        ),
        migrations.AddField(
            model_name='animal',
            name='specie',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='VetApp.Specie'),
        ),
    ]
